#1st line is the namespace of the controller
single_joint_actuator: 
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
   
    # Position Controllers ---------------------------------------
    joint1_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint1
      pid: {p: 30.0, i: 0.03, d: 0.0, i_clamp_min: -130.0, i_clamp_max: 130, antiwindup: True} 
      
    # Velocity Controllers ---------------------------------------
    rwheel:
      type: effort_controllers/JointVelocityController
      joint: joint1
      # these PID coffections are tunned and perfectly work btw 0.3 rad/s to 9 rad/s
      #pid: {p: 1.7, i: 0.0006, d: 0, i_clamp_min: -100.0, i_clamp_max: 100, antiwindup: True}
      pid: {p: 0, i: 0.0, d: 0.0, i_clamp_min: -255.0, i_clamp_max: 255, antiwindup: True}

      #pid: {p: 12.5, i: 3.65, d: 0.5, i_clamp_min: -255.0, i_clamp_max: 255, antiwindup: True}

    # lwheel is the topic for h/w interface to publish
    lwheel:
      type: effort_controllers/JointVelocityController
      joint: joint2
      # these PID coffections are tunned and perfectly work btw 0.3 rad/s to 9 rad/s
      #pid: {p: 1.1, i: 0.00162, d: 0, i_clamp_min: -255.0, i_clamp_max: 255, antiwindup: True}
      pid: {p: 6.5, i: 0.00, d: 0.0, i_clamp_min: -255.0, i_clamp_max: 255, antiwindup: True}

      #pid: {p: 1.2, i: 1.94, d: 0.5, i_clamp_min: -255.0, i_clamp_max: 255, antiwindup: True}

    wheel_separation : 0.15
    wheel_radius : 0.035
    ticks_meter : 3665 # 1/(2 x pi x wheel_radius) * N
