#1st line is the namespace of the controller, may be can get rid of it later for simplicity
mbot:  
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    
    # Position Controllers ---------------------------------------
    joint1_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint1
      pid: {p: 30.0, i: 0.03, d: 0.0, i_clamp_min: -130.0, i_clamp_max: 130, antiwindup: True} 
      
    # Velocity Controllers ---------------------------------------
    joint1_velocity_controller:
      type: effort_controllers/JointVelocityController
      joint: joint1
      # these PID coffections are tunned and perfectly work btw 0.3 rad/s to 9 rad/s
      pid: {p: 6, i: 12, d: 0, i_clamp_min: -255.0, i_clamp_max: 255, antiwindup: True}
      #pid: {p: 1.2, i: 1.94, d: 0.5, i_clamp_min: -255.0, i_clamp_max: 255, antiwindup: True}'

    # left joint
    joint2_velocity_controller:
      type: effort_controllers/JointVelocityController
      joint: joint2
      # these PID coffections are tunned and perfectly work btw 0.3 rad/s to 9 rad/s
      pid: {p: 6, i: 12, d: 0, i_clamp_min: -255.0, i_clamp_max: 255, antiwindup: True}

    wheel_separation : 0.2
    wheel_radius : 0.035    